# Mapping Data Metadata
# This file describes the structure and organization of mapping files

[metadata]
version = "1.0"
description = "Shlesha script conversion mappings"

[scripts]
# Roman scripts (no implicit 'a')
roman = ["iast", "itrans", "slp1", "harvard_kyoto", "velthuis", "wx", "iso15919"]

# Indic scripts (have implicit 'a')
indic = ["devanagari", "bengali", "gujarati", "tamil", "telugu", "kannada", "malayalam", "odia", "gurmukhi"]

[hub]
# Central hub scripts for conversion
roman_hub = "iso15919"
indic_hub = "devanagari"

[mapping_types]
# Types of mappings in base files
vowels = "Independent vowels"
consonants = "Consonants (without inherent vowel)"
vowel_marks = "Vowel diacritical marks"
special = "Special characters (anusvara, visarga, etc.)"
punctuation = "Punctuation and symbols"
numerals = "Numeric digits"