[metadata]
script = "slp1"
script_type = "roman"
has_implicit_a = false
description = "Sanskrit Library Phonetic encoding"

[to_iso.vowels]
"a" = "a"
"A" = "ā"
"i" = "i"
"I" = "ī"
"u" = "u"
"U" = "ū"
"f" = "r̥"
"F" = "r̥̄"
"x" = "l̥"
"X" = "l̥̄"
"e" = "e"
"o" = "o"
"E" = "ai"
"O" = "au"

[to_iso.consonants]
"k" = "k"
"K" = "kh"
"g" = "g"
"G" = "gh"
"N" = "ṅ"
"c" = "c"
"C" = "ch"
"j" = "j"
"J" = "jh"
"Y" = "ñ"
"w" = "ṭ"
"W" = "ṭh"
"q" = "ḍ"
"Q" = "ḍh"
"R" = "ṇ"
"t" = "t"
"T" = "th"
"d" = "d"
"D" = "dh"
"n" = "n"
"p" = "p"
"P" = "ph"
"b" = "b"
"B" = "bh"
"m" = "m"
"y" = "y"
"r" = "r"
"l" = "l"
"v" = "v"
"S" = "ś"
"z" = "ṣ"
"s" = "s"
"h" = "h"
"L" = "ḷ"

[to_iso.marks]
"M" = "ṁ"
"H" = "ḥ"
"~" = "m̐"
"|" = " "
"||" = " "

[to_iso.digits]
"0" = "0"
"1" = "1"
"2" = "2"
"3" = "3"
"4" = "4"
"5" = "5"
"6" = "6"
"7" = "7"
"8" = "8"
"9" = "9"