[metadata]
script = "velthuis"
script_type = "roman"
has_implicit_a = false
description = "Velthuis ASCII transliteration scheme developed by Frans Velthuis"

[to_iso.vowels]
"a" = "a"
"aa" = "ā"
"A" = "ā"
"i" = "i"
"ii" = "ī"
"I" = "ī"
"u" = "u"
"uu" = "ū"
"U" = "ū"
".r" = "r̥"
".R" = "r̥̄"
".l" = "l̥"
".L" = "l̥̄"
"e" = "e"
"ai" = "ai"
"o" = "o"
"au" = "au"

[to_iso.consonants]
"k" = "k"
"kh" = "kh"
"g" = "g"
"gh" = "gh"
"\"n" = "ṅ"
"c" = "c"
"ch" = "ch"
"j" = "j"
"jh" = "jh"
"~n" = "ñ"
".t" = "ṭ"
".th" = "ṭh"
".d" = "ḍ"
".dh" = "ḍh"
".n" = "ṇ"
"t" = "t"
"th" = "th"
"d" = "d"
"dh" = "dh"
"n" = "n"
"p" = "p"
"ph" = "ph"
"b" = "b"
"bh" = "bh"
"m" = "m"
"y" = "y"
"r" = "r"
"l" = "l"
"v" = "v"
"\"s" = "ś"
".s" = "ṣ"
"s" = "s"
"h" = "h"
".ll" = "ḷ"

[to_iso.nukta]
"q" = "q"
"f" = "f"
"z" = "z"

[to_iso.special]
"k.s" = "kṣ"
"j~n" = "jñ"

[to_iso.marks]
".m" = "ṁ"
".h" = "ḥ"
"~" = "m̐"
"'" = "'"