[metadata]
script = "wx"
script_type = "roman"
has_implicit_a = false
description = "WX notation developed by IIIT Hyderabad for computational linguistics"

[to_iso.vowels]
"a" = "a"
"A" = "ā"
"i" = "i"
"I" = "ī"
"u" = "u"
"U" = "ū"
"e" = "e"
"E" = "ai"
"o" = "o"
"O" = "au"
"q" = "r̥"
"Q" = "r̥̄"
"L" = "l̥"
"lY" = "l̥̄"

[to_iso.consonants]
"k" = "k"
"K" = "kh"
"g" = "g"
"G" = "gh"
"f" = "ṅ"
"c" = "c"
"C" = "ch"
"j" = "j"
"J" = "jh"
"F" = "ñ"
"w" = "ṭ"
"W" = "ṭh"
"x" = "ḍ"
"X" = "ḍh"
"N" = "ṇ"
"t" = "t"
"T" = "th"
"d" = "d"
"D" = "dh"
"n" = "n"
"p" = "p"
"P" = "ph"
"b" = "b"
"B" = "bh"
"m" = "m"
"y" = "y"
"r" = "r"
"l" = "l"
"v" = "v"
"S" = "ś"
"z" = "ṣ"
"s" = "s"
"h" = "h"
"lZ" = "ḷ"

[to_iso.nukta]
"kZ" = "q"
"KZ" = "ḵẖ"
"gZ" = "ġ"
"jZ" = "z"
"dZ" = "ṛ"
"DZ" = "ṛh"
"pZ" = "f"
"yZ" = "ẏ"

[to_iso.special]
"kz" = "kṣ"
"jF" = "jñ"
"wR" = "tr"

[to_iso.marks]
"M" = "ṁ"
"H" = "ḥ"
"Z" = "m̐"
"'" = "'"