# IAST (International Alphabet of Sanskrit Transliteration) mappings

[metadata]
script = "iast"
script_type = "roman"
has_implicit_a = false

[to_iso]
# IAST to ISO-15919 mappings

[to_iso.vowels]
"a" = "a"
"ā" = "ā"
"i" = "i"
"ī" = "ī"
"u" = "u"
"ū" = "ū"
"ṛ" = "r̥"     # IAST ṛ → ISO r̥
"ṝ" = "r̥̄"    # IAST ṝ → ISO r̥̄
"ḷ" = "l̥"     # IAST ḷ → ISO l̥
"ḹ" = "l̥̄"    # IAST ḹ → ISO l̥̄
"e" = "e"
"ai" = "ai"
"o" = "o"
"au" = "au"

[to_iso.consonants]
# Bare consonants (without inherent vowel)
"k" = "k"
"kh" = "kh"
"g" = "g"
"gh" = "gh"
"ṅ" = "ṅ"
"c" = "c"
"ch" = "ch"
"j" = "j"
"jh" = "jh"
"ñ" = "ñ"
"ṭ" = "ṭ"
"ṭh" = "ṭh"
"ḍ" = "ḍ"
"ḍh" = "ḍh"
"ṇ" = "ṇ"
"t" = "t"
"th" = "th"
"d" = "d"
"dh" = "dh"
"n" = "n"
"p" = "p"
"ph" = "ph"
"b" = "b"
"bh" = "bh"
"m" = "m"
"y" = "y"
"r" = "r"
"l" = "l"
"v" = "v"
"ś" = "ś"
"ṣ" = "ṣ"
"s" = "s"
"h" = "h"

[to_iso.special]
"ṃ" = "ṁ"      # IAST anusvara → ISO anusvara
"ḥ" = "ḥ"      # visarga (same)
"'" = "'"      # avagraha (same)
"ṁ" = "ṁ"      # alternate anusvara
"m̐" = "m̐"      # candrabindu (same)

[from_iso]
# Reverse mappings where different from simple inversion
"r̥" = "ṛ"      # ISO r̥ → IAST ṛ
"r̥̄" = "ṝ"     # ISO r̥̄ → IAST ṝ
"l̥" = "ḷ"      # ISO l̥ → IAST ḷ
"l̥̄" = "ḹ"     # ISO l̥̄ → IAST ḹ
"ṁ" = "ṃ"      # ISO anusvara → IAST anusvara