# ISO-15919 to Devanagari mappings
# This is the central hub mapping for Indic scripts

[metadata]
from_script = "iso15919"
to_script = "devanagari"
from_type = "roman"
to_type = "indic"
from_has_implicit_a = false
to_has_implicit_a = true

[mappings.vowels]
# Independent vowels
"a" = "अ"
"ā" = "आ"
"i" = "इ"
"ī" = "ई"
"u" = "उ"
"ū" = "ऊ"
"r̥" = "ऋ"
"r̥̄" = "ॠ"
"l̥" = "ऌ"
"l̥̄" = "ॡ"
"e" = "ए"
"ai" = "ऐ"
"o" = "ओ"
"au" = "औ"

[mappings.consonants]
# Consonants with inherent 'a'
"ka" = "क"
"kha" = "ख"
"ga" = "ग"
"gha" = "घ"
"ṅa" = "ङ"
"ca" = "च"
"cha" = "छ"
"ja" = "ज"
"jha" = "झ"
"ña" = "ञ"
"ṭa" = "ट"
"ṭha" = "ठ"
"ḍa" = "ड"
"ḍha" = "ढ"
"ṇa" = "ण"
"ta" = "त"
"tha" = "थ"
"da" = "द"
"dha" = "ध"
"na" = "न"
"pa" = "प"
"pha" = "फ"
"ba" = "ब"
"bha" = "भ"
"ma" = "म"
"ya" = "य"
"ra" = "र"
"la" = "ल"
"va" = "व"
"śa" = "श"
"ṣa" = "ष"
"sa" = "स"
"ha" = "ह"

[mappings.vowel_marks]
# Vowel diacritical marks (mātrās)
# Note: These are for composition, not direct mapping
"ā" = "ा"
"i" = "ि"
"ī" = "ी"
"u" = "ु"
"ū" = "ू"
"r̥" = "ृ"
"r̥̄" = "ॄ"
"l̥" = "ॢ"
"l̥̄" = "ॣ"
"e" = "े"
"ai" = "ै"
"o" = "ो"
"au" = "ौ"

[mappings.special]
# Special marks
"" = "्"      # virama (halant) - used to remove inherent 'a'
"m̐" = "ँ"     # candrabindu
"ṁ" = "ं"     # anusvara
"ḥ" = "ः"     # visarga
"'" = "ऽ"     # avagraha
"oṁ" = "ॐ"    # om symbol

[mappings.numerals]
# Devanagari numerals
"0" = "०"
"1" = "१"
"2" = "२"
"3" = "३"
"4" = "४"
"5" = "५"
"6" = "६"
"7" = "७"
"8" = "८"
"9" = "९"

[composition_rules]
# Rules for composing characters
# Format: "context + addition = result"
consonant_virama = "Consonant + virama removes inherent 'a'"
consonant_vowel = "Consonant + vowel mark replaces inherent 'a'"